version: '3.5'

services:
  db:
    image: postgres:10.4
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data

  api:
    build: .
    volumes:
      - .:/usr/src/app/
    ports:
      - '8080:80'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - "db"
    command: ["./scripts/wait-for-it.sh", "db:5432", "--", "npm", "start"] # Wait for postgres
